disableKinds = ["taxonomy", "taxonomyTerm"]
disablePathToLower = true
disqusShortname = "my-site"
enableGitInfo = true
googleAnalytics = "UA-XXXXXXXXX-X"
[params]
BookComments = true
BookDateFormat = "Jan 2, 2006"
BookEditPath = "edit/master/exampleSite"
BookLogo = "logo.png"
BookMenuBundle = "/menu"
BookPortableLinks = true
BookRepo = "https://github.com/alex-shpak/hugo-book"
BookSearch = true
BookSection = "docs"
BookServiceWorker = true
BookToC = true
